package utils

var RatingScore = map[string]int{
	"Top Pick":            10,
	"Strong-Buy":          9,
	"Buy":                 8,
	"Outperform":          7,
	"Mkt Outperform":      7,
	"Market Outperform":   7,
	"Overweight":          6,
	"Moderate Buy":        6,
	"Positive":            6,
	"Speculative Buy":     6,
	"Outperformer":        5,
	"Sector Outperform":   5,
	"Equal Weight":        4,
	"In-Line":             4,
	"Peer Perform":        4,
	"Market Perform":      3,
	"Sector Perform":      3,
	"Sector Weight":       3,
	"Neutral":             2,
	"Hold":                2,
	"Underweight":         1,
	"Underperform":        1,
	"Sector Underperform": 1,
	"Underperformer":      1,
	"Sell":                0,
}
